apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: akox45/projekt:tagname
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword 
        - name: MYSQL_DATABASE
          value: mydatabase 
        - name: MYSQL_USER
          value: myuser
        - name: MYSQL_PASSWORD
          value: mypassword 
        ports:
        - containerPort: 3306
